### ISSUE TITLE
Source ≠ Structure = Mess?

### ISSUE THREAD

**Issue by signalwerk** [matthewepler/ReCode_Project#13]
I'd like to order the translations (sketches) a bit more meaningful. 
If some people agree I'd start the ordening. 

Any Ideas for the structure?

Maybe: 
src/(artistsFamilyName artistsFirstName)/(name of publication)/(Issue)/(name of work)/

Better Ideas? The initial author of the sketch would be in the source. I'd do the ordening of the source. But the Webpage-Generator should also be adjusted.

**Comment by matthewepler** [comment]
I agree, this should be added. All of those fields are in the JSON objects with one exception, the artist name is a single string, so you'd have to split it in order to sort by family name. 

The site is not being generated by the GitHub pages option. It's a standalone Flask app running on Heroku. If you'd like to take a look at the code, it's in a repo called "recodesite" on my GitHub page. 

Thanks for bringing this up. It's a great point.

Matt Epler

**Comment by signalwerk** [comment]
hi @matthewepler right now I'm traveling till beginning of January. But I try to catch up on several different things here in that repro in the next days. Thanks for the work you did in the last days! Great!

**Comment by matthewepler** [comment]
Thanks, Stefan. Best holiday wishes.

Matt Epler

On Tue, Dec 25, 2012 at 2:34 AM, Stefan Huber notifications@github.comwrote:

> hi @matthewepler https://github.com/matthewepler right now I'm
> traveling till beginning of January. But I try to catch up on several
> different things here in that repro in the next days. Thanks for the work
> you did in the last days! Great!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/matthewepler/ReCode_Project/issues/13#issuecomment-11670255.

## 

Matthew Epler
http://mepler.com
